'use strict';
const { Lionel } = require("lionel-app/bin/LionelClass");
const Router = Lionel.Router;
Router.route('/index');
Router.route('/', 'index');
Router.route('/Home', 'index');
Router.route('/Docs', 'Docs');
Router.route('/About', 'About');
Router.route('/Getting Started', 'Getting Started');
Router.route('/Install', 'Install');
Router.route('/LionelClient', 'LionelClient');
Router.route('/Methods', 'Methods');
Router.route('/PHP', 'PHP');
Router.route('/Routes', 'Routes');
Router.route('/Structure', 'Structure');